### ISSUE TITLE
rotating & flipping crashing for larger selections

### ISSUE THREAD

**Issue by Dominik282004** [platz1de/EasyEdit#82]
if I enter //rotate 90 to rotate something, it always says that 0 blocks were copied although I entered //copy beforehand and if I enter //paste what I copied comes up but it is no longer rotated by //rotate

**Comment by platz1de** [comment]
Rotate shouldn't say that that blocks were copied to begin with
Please make sure you run 3.0.1 which fixed some issues related to rotating and / or comment the full comand outputs here

**Comment by Dominik282004** [comment]
I tested it a bit and saw that //rotate works but only if you have copied under 3.5k blocks beforehand, everything above that doesn't work

**Comment by CoolCuzzy** [comment]
Yeah i just came to report this problem. Whilst building i was attempting to copy and rotate, but it kept saying 0 blocks were rotated unless its under a small amount of blocks. If it’s under a small amount of blocks (im not sure exactly what but it wouldnt allow me to rotate with larger counts) it works.

This is kind of a big issue because it’s just delayed everything and i have to build something multiple times which delays things by 4x longer. 

Please fix this issue ASAP!!

**Comment by Matze997** [comment]
I´ve got that error message:

[14:17:31.558] [EasyEdit editing thread/CRITICAL]: Exception: "Cannot traverse an already closed generator" (EXCEPTION) in "/home/rayve/Minecraft/Bedrock/RayveEU/Standalone/Bedrock-Bauserver/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/DynamicStoredRotateTask" at line 65
--- Stack trace ---
  #0 /home/rayve/Minecraft/Bedrock/RayveEU/Standalone/Bedrock-Bauserver/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/ExecutableTask(39): platz1de\EasyEdit\task\DynamicStoredRotateTask->executeInternal()
  #1 /home/rayve/Minecraft/Bedrock/RayveEU/Standalone/Bedrock-Bauserver/plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/EditThread(76): platz1de\EasyEdit\task\ExecutableTask->run()
  #2 pmsrc/src/thread/CommonThreadPartsTrait(109): platz1de\EasyEdit\thread\EditThread->onRun()
  #3 (): pocketmine\thread\Thread->run()
--- End of exception information ---
